### ISSUE TITLE
`SendNotifyMessage()` might not be the right function to broadcast a string

### ISSUE THREAD

**Issue by german-one** [lhecker/windows-dark-mode-switcher#1]
When I've seen you using this function I remembered that I tried it out for exactly the same reason some time ago. The difference is that I wrapped it into a piece of C# code to make it usable in a PowerShell `Add-Type` definition. At least the function name indicates that it is made for this purpose and I found it quite comfortable that it returns instantly and that it is still readable with only four parameters, compared with the seven parameters of `SendMessageTimeout()`.  
However, `SendNotifyMessage()` didn't work reliably for me. Every now and then the mode didn't change immediatelly. E.g. the color of the taskbar didn't change or taskbar icons turned into something like high contrast style. I can't reproduce this bug with your C code. Using `SendMessageTimeout()` was what I had to do to fix my code though. `SendNotifyMessage()` returns immediatelly when used along whith `HWND_BROADCAST`, which makes the string pointer it sends to the message queues a dangling pointer.  

https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendnotifymessagew#remarks  
> If you send a message in the range below WM_USER to the asynchronous message functions (PostMessage, SendNotifyMessage, and SendMessageCallback), its message parameters cannot include pointers. Otherwise, the operation will fail. The functions will return before the receiving thread has had a chance to process the message and the sender will free the memory before it is used.

**Comment by lhecker** [comment]
> [...] and the sender will free the memory before it is used.

That's an unusually bold assumption by the author of the documentation. Not all pointers must refer to dynamic memory allocations. In this case it refers to a string literal, which resides in the constant `.rodata` segment of the application. In other words, it'll never become invalid, because it's a pointer into global constant storage.

But this raises another great point that I never thought about: When you send out a `HWND_BROADCAST` message, how do other applications access your pointer? Since the string literal resides in my application's address space, other applications cannot possibly access that memory just by using the pointer as is. This proves that the kernel must be copying the LPARAM string into each receiver's address space.

I guess that means that using `SendNotifyMessage` with such a literal is safe?

**Comment by german-one** [comment]
> But this raises another great point that I never thought about: When you send out a `HWND_BROADCAST` message, how do other applications access your pointer? Since the string literal resides in my application's address space, other applications cannot possibly access that memory just by using the pointer as is. This proves that the kernel must be copying the LPARAM string into each receiver's address space. This proves that the kernel must be copying the LPARAM string into each receiver's address space.  

My assumption was indeed that the string is copied. Now it depends what it actually means if `SendNotifyMessage` returns "immediatelly". If sending the message to all top level windows happens if the function already returned, then you're already about to tear down your process as the next thing in your code is returning from main. So, the address space of your process is getting invalid, and `.rodata` or not doesn't matter anymore. At least that's my humble understanding 😅

**Comment by lhecker** [comment]
Yeah, so I think `SendNotifyMessage` should be ideal for this scenario. It just posts the notification into the message queue of all processes and then immediately exits without waiting (= efficient). Since the OS copies the string literal there are no lifetime/reference issues.

Apropos...

> [...] as the next thing in your code is returning from main.

I'm currently working on the first "full" version of this tool over in the https://github.com/lhecker/windows-dark-mode-switcher/tree/wip branch. My goal is to make the scheduled time configurable, as well as allowing the tool to register itself as a scheduled task. So basically, you just put it somewhere run `dark-mode-switcher.exe register 06:00 18:00` and it'll do the entire event scheduler thing for you. I just haven't had enough time last weekend to finish it. 😅
(If you want to give it a try to finish the branch, please feel free to do so. Otherwise, I'll let you know once I'm done, if you're interested in this project.)

**Comment by german-one** [comment]
I'm still wondering what difference it makes if it is p/invoked from a PowerShell script then. However, that's not a topic that belongs to here 😊 I'll definitely try your update and let you know. (COM interfaces in C are fun 😄)   
BTW you could optionally let the users pass their longitude and latitude and calculate the real sunrise and sunset time from the current date. Of course respecting daylight saving time and stuff 🤣 Although I'm afraid you'll never be bored enough to implement things like that.

**Comment by lhecker** [comment]
> I'm still wondering what difference it makes if it is p/invoked from a PowerShell script then.

Was your issue with string literals or another type of pointer? And was it with a `HWND_BROADCAST` message? I wonder if it fails to work in C# because it copies string literals into the heap? Perhaps it GC's them at random times...

> Although I'm afraid you'll never be bored enough to implement things like that.

That's actually right up my alley. 😅

**Comment by german-one** [comment]
I don't remember the old code in detail. It's been a predecessor of that code with `SendNotifyMessage` in place of `SendMessageTimeout`.  

<details>
<summary>Click to expand</summary>

```Powershell
Add-Type @'
using Microsoft.Win32;
using System;
using System.Runtime.InteropServices;
namespace Theme {
  public enum Mode { Dark, Light, Toggle }

  public static class P13n {
    private static readonly IntPtr n0 = IntPtr.Zero, NULL = IntPtr.Zero, HWND_BROADCAST = new IntPtr(0xFFFF);
    private const int WM_SETTINGCHANGE = 0x001A, SMTO_ABORTIFHUNG = 0x0002;
    private const string areaICS = "ImmersiveColorSet";

    [DllImport("kernel32.dll", SetLastError = true)]
    private static extern void SetLastError(int err);
    [DllImport("user32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
    private static extern IntPtr SendMessageTimeout(IntPtr hw, int m, IntPtr wp, string lp, int f, int tout, IntPtr r);

    private static void BroadcastP13nChanges() {
      SetLastError(0);
      if (n0 == SendMessageTimeout(HWND_BROADCAST, WM_SETTINGCHANGE, n0, areaICS, SMTO_ABORTIFHUNG, 5000, NULL) ||
          0 != Marshal.GetLastWin32Error()) {
        throw new TimeoutException("Setting changes broadcasted incompletely.");
      }
    }

    private static RegistryKey GetP13nKey() {
      return Registry.CurrentUser.CreateSubKey(@"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize");
    }

    private static bool SetBoolAsI4(string name, bool one) {
      bool old;
      using(RegistryKey p13n = GetP13nKey()) {
        old = (0 != (int)p13n.GetValue(name, 0));
        p13n.SetValue(name, one ? 1 : 0);
      }
      BroadcastP13nChanges();
      return old;
    }

    public static Mode SetMode(Mode mode) {
      Mode old;
      using(RegistryKey p13n = GetP13nKey()) {
        old = (0 == (int)p13n.GetValue("SystemUsesLightTheme", 0)) ? Mode.Dark : Mode.Light;
        int use = (Mode.Light == mode || (Mode.Toggle == mode && Mode.Dark == old)) ? 1 : 0;
        p13n.SetValue("SystemUsesLightTheme", use);
        p13n.SetValue("AppsUseLightTheme", use);
      }
      BroadcastP13nChanges();
      return old;
    }

    public static bool EnableTransparency(bool apply) {
      return SetBoolAsI4("EnableTransparency", apply);
    }

    public static bool EnableTaskbarColor(bool apply) {
      return SetBoolAsI4("ColorPrevalence", apply);
    }
  }
}
'@

# Start > Settings > Personalization > Colors > ...
# ... Choose your mode
$prevMode = [Theme.P13n]::SetMode([Theme.Mode]::Toggle)
Write-Output "Previous mode: $prevMode"

# ... Transparency effects
#$wasTransp = [Theme.P13n]::EnableTransparency($True)
#Write-Output "Transparency effects were used: $wasTransp"

# ... Show accent color on Start and taskbar
#$hadTaskbarCol = [Theme.P13n]::EnableTaskbarColor($False)
#Write-Output "Start and taskbar were colored: $hadTaskbarCol"

pause
```

</details>
<br>
  
> That's actually right up my alley. 😅  

That'd be so cool 🤣

**Comment by german-one** [comment]
> I'll definitely try your update and let you know.  

Well, at a first glance ...  
That's my command line:  
`"dark-mode-switcher.exe" register "06:00" "18:00"`  
It creates a scheduled task as expected. But I would have expected to find the triggers at the defined times.  
<img width="473" alt="Screenshot 2024-10-16 180201" src="https://github.com/user-attachments/assets/b4d40fef-0741-456e-bcd7-7582d20c7845">  
  
EDIT OK, it's a WIP. So you don't use the converted times yet. Got it 😊 The switch command works well.

**Comment by german-one** [comment]
Oh look at that! After some more testing with the `switch` command I got the same bug that I discribed 😯
<img width="959" alt="Screenshot 2024-10-16 184707" src="https://github.com/user-attachments/assets/cfa6e0fe-67ad-4208-baa3-eae11455cafe">
This should have been light mode. The explorer window turned into light, also the text color in the notification area of the taskbar turned to black. However, the taskbar is still dark.

**Comment by lhecker** [comment]
I see... So perhaps your intuition was right on the mark after all! Thanks for testing this!

**Comment by german-one** [comment]
I just hope my system isn't screwed up. Perhaps leave it as is for now and wait for feedback of more people 🤷‍♂️

**Comment by german-one** [comment]
Off topic:  
I have a proof of concept. Feel free to grab whatever you think is helpful for you 😄  
https://github.com/german-one/windows-dark-mode-switcher/tree/dynamic

**Comment by lhecker** [comment]
If you'd like we can also merge it as-is (or when you think it's ready) as this may be the best way to attribute it as your code. I have a few changes in mind (the biggest one would be to abstract the task creation away somewhat to deduplicate it), but it generally looks good to me!

You can of course also keep it in your fork and we just work on separate versions while cross merging each other's advancements. I wouldn't mind that either, since it's just a small toy project anyway. And I definitely won't mind either if you're copying code from me that you consider helpful. 😅

**Comment by german-one** [comment]
> If you'd like we can also merge it as-is  

Of course we can. I wasn't sure if you even like it as it adds a lot of new code and I know there is still a lot room for improvements. As our apartment is currently under construction I'm afraid I won't have time for further working on the code anytime soon.  

> (the biggest one would be to abstract the task creation away somewhat to deduplicate it)  

Yes thats what I had in mind when I decided to take over the daily triggers even for the dynamically updated task. This should make deduplicating easier. FWIW The additional logon trigger seemed logical to me at first. Meanwhile I believe this might be unnecessary. The other triggers should fire as soon as posible when they become overdue.
